"""init

Revision ID: b55d222757e9
Revises: 
Create Date: 2026-08-06 12:11:07.219338+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b55d222757e9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organisations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('secteur', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('telephone', sa.String(length=30), nullable=True),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('agences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('adresse', sa.String(length=500), nullable=True),
    sa.Column('ville', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('seuil_alerte', sa.Float(), nullable=False),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qr_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agence_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agence_id'], ['agences.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('utilisateurs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('agence_id', sa.UUID(), nullable=True),
    sa.Column('nom', sa.String(length=150), nullable=False),
    sa.Column('prenom', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('mot_de_passe_hash', sa.String(length=500), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'CX_MANAGER', 'AGENCY_MANAGER', name='userrole'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('derniere_connexion', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agence_id'], ['agences.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('feedbacks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('qr_code_id', sa.UUID(), nullable=False),
    sa.Column('note', sa.Integer(), nullable=False),
    sa.Column('commentaire', sa.String(length=1000), nullable=True),
    sa.Column('date_soumission', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['qr_code_id'], ['qr_codes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historique_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('utilisateur_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=200), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('entite_type', sa.String(length=100), nullable=True),
    sa.Column('entite_id', sa.String(length=100), nullable=True),
    sa.Column('adresse_ip', sa.String(length=50), nullable=True),
    sa.Column('date_action', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analyses_ia',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('feedback_id', sa.UUID(), nullable=False),
    sa.Column('sentiment', sa.Enum('POSITIF', 'NEUTRE', 'NEGATIF', name='sentimenttype'), nullable=False),
    sa.Column('criticite', sa.Enum('FAIBLE', 'MOYENNE', 'ELEVEE', 'CRITIQUE', name='criticitetype'), nullable=False),
    sa.Column('theme_principal', sa.String(length=100), nullable=True),
    sa.Column('discordance_detectee', sa.Boolean(), nullable=False),
    sa.Column('score_sentiment', sa.Float(), nullable=True),
    sa.Column('date_analyse', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedbacks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feedback_id')
    )
    op.create_table('demandes_contact',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('feedback_id', sa.UUID(), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=True),
    sa.Column('telephone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('souhaite_etre_rappele', sa.Boolean(), nullable=False),
    sa.Column('date_demande', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('traitee', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedbacks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feedback_id')
    )
    op.create_table('suggestions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('feedback_id', sa.UUID(), nullable=False),
    sa.Column('contenu', sa.Text(), nullable=False),
    sa.Column('statut', sa.Enum('NOUVEAU', 'EN_COURS', 'TRAITE', 'REJETE', name='ideastatus'), nullable=False),
    sa.Column('date_soumission', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_traitement', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes_internes', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedbacks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historique_suggestions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('suggestion_id', sa.UUID(), nullable=False),
    sa.Column('ancien_statut', sa.Enum('NOUVEAU', 'EN_COURS', 'TRAITE', 'REJETE', name='ideastatus'), nullable=True),
    sa.Column('nouveau_statut', sa.Enum('NOUVEAU', 'EN_COURS', 'TRAITE', 'REJETE', name='ideastatus'), nullable=False),
    sa.Column('commentaire', sa.String(length=500), nullable=True),
    sa.Column('date_action', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('utilisateur_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['suggestion_id'], ['suggestions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommandations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analyse_ia_id', sa.UUID(), nullable=False),
    sa.Column('contenu', sa.Text(), nullable=False),
    sa.Column('priorite', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='prioritylevel'), nullable=False),
    sa.Column('date_generation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('traitee', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['analyse_ia_id'], ['analyses_ia.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recommandations')
    op.drop_table('historique_suggestions')
    op.drop_table('suggestions')
    op.drop_table('demandes_contact')
    op.drop_table('analyses_ia')
    op.drop_table('historique_actions')
    op.drop_table('feedbacks')
    op.drop_table('utilisateurs')
    op.drop_table('qr_codes')
    op.drop_table('agences')
    op.drop_table('organisations')
    # ### end Alembic commands ###
